sudo: true
dist: trusty 
sudo: require
     
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
compiler:
  - gcc
  - clang  
env:
  matrix:
    - BUILD_TYPE=debug   VERBOSE_MAKE=true
    - BUILD_TYPE=   VERBOSE_MAKE=true
matrix:
  allow_failures:
    - env BUILD_TYPE=debug
notifications:
  email: false  
git:
  submodules: false
  # depth: 3
branches:
  except: 
    - gh-pages
script:
  - [ -e ./scripts/stats_binary_search.sh ] && ./scripts/stats_binary_search.sh || echo "binary_search not found" 
  - echo $?


 
