sudo: true
language: c++
dist: trusty 
sudo: require
linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
compiler:
  - gcc
  - clang  
env:
  matrix:
    - BUILD_TYPE=debug   VERBOSE_MAKE=true
    - BUILD_TYPE=   VERBOSE_MAKE=true
matrix:
  allow_failures:
    - env BUILD_TYPE=debug
notifications:
  email: false  
git:
  submodules: false
  depth: 3
before_install:
 - sudo -s apt update && sudo -s apt install coreutils
addons:
  apt:
    packages:
      - coreutils
branches:
  except: 
    - gh-pages
script:
  - ./scripts/stats_binary_search.sh
  - echo $? 
