
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.equalTo;

public class BinaryGapTest {
    @Test
    public void testBinaryGap() {
        BinaryGap clazz = new BinaryGap();
                
        assertEquals((long)5, (long)clazz.execute(232323));
        assertThat(clazz.execute(232323), is(equalTo(5)));
    }
}
