#!/usr/bin/env bash
#
# Installs and executes several development environments
###

SCRIPT_PATH=$(realpath $(dirname $0))
ROOT_PATH=$(realpath $SCRIPT_PATH/..)
perf=$ROOT_PATH/perf.log

if  ! which umake > /dev/null; then
    sudo apt install umake
fi

if  ! which node > /dev/null; then
    umake nodejs
    export PATH=$PATH:~/.local/share/umake/nodejs/nodejs-lang/bin
fi

if  ! which perl6 > /dev/null; then
    sudo apt install perl6
fi

if ! which go > /dev/null; then
    umake go
    export GOROOT=/home/username/.local/share/umake/go/go-lang
    export PATH=/home/username/.local/share/umake/go/go-lang/bin:$PATH
fi

if ! which octave-cli > /dev/null; then
    sudo apt install octave-cli
fi

if ! which php > /dev/null; then
    sudo apt install php7.0-cli
fi

if ! which ruby > /dev/null; then
    sudo apt install ruby
fi

