#!/usr/bin/env bash
#
# Installs and executes several development environments
###

function set_env() {
    if  ! which realpath >/dev/null; then
        echo  'coreutils is not installed, realpath and dirname are not available'
        echo `uname -a`
        export SCRIPT_PATH=${BASH_SOURCE%/*}
        export ROOT_PATH=${SCRIPT_PATH%/*}
        export REQUIREMENTS_JAVA_PATH=$ROOT_PATH/requirements_java
        echo BASH_SOURCE: $BASH_SOURCE
        echo \$0\: $0
        echo SCRIPT_PATH: $SCRIPT_PATH 
        echo ROOT_PATH: $ROOT_PATH  
        echo REQUIREMENTS_JAVA_PATH: $REQUIREMENTS_JAVA_PATH
        echo --------------------------

        # Ubuntu trusty does not have php
        sudo apt-add-repository ppa:ondrej/php
        sudo apt-get update    

    else
        export SCRIPT_PATH=$(realpath $(dirname $BASH_SOURCE))
        export ROOT_PATH=$(realpath $SCRIPT_PATH/..)
        export REQUIREMENTS_JAVA_PATH=$ROOT_PATH/requirements_java

        echo BASH_SOURCE: $(realpath $BASH_SOURCE)
        echo \$0\: $(realpath $0)
        echo SCRIPT_PATH: $SCRIPT_PATH 
        echo ROOT_PATH: $ROOT_PATH  
        echo REQUIREMENTS_JAVA_PATH: $REQUIREMENTS_JAVA_PATH
        echo --------------------------
    fi
}

set_env

if  ! which umake > /dev/null; then
    sudo apt install umake
fi

if  ! which node > /dev/null; then
    umake nodejs
    export PATH=$PATH:~/.local/share/umake/nodejs/nodejs-lang/bin
    npm i -g npm
fi

if  ! which perl6 > /dev/null; then
    sudo apt install perl6
fi

echo perl6 -v

if ! which go > /dev/null; then
    umake go
    export GOROOT=/home/username/.local/share/umake/go/go-lang
    export PATH=/home/username/.local/share/umake/go/go-lang/bin:$PATH
fi

if ! which octave-cli > /dev/null; then
    sudo apt install octave-cli
fi

if ! which php > /dev/null; then    
    sudo apt install php7.0-cli
fi

if ! which hhvm > /dev/null; then
    sudo apt install hhvm
fi

if [ $(php --version | head -1 | cut -d' ' -f2 | cut -d'.' -f1) -lt 7 ]; then
    sudo apt install php7.0-cli
fi

if ! which ruby > /dev/null; then
    sudo apt install ruby
fi

